---
- name: Run cis hardening
  hosts: all
  gather_facts: true
  roles:
    - role_cis
  post_tasks:
    - name: Reload firewall
      ansible.builtin.shell: "iptables -P OUTPUT ACCEPT"
      become: true
