---
  - name: Install and configure ModSecurity with OWASP CRS for Juice Shop
    hosts: webserver
    become: yes
    tasks:
  
      - name: Gather facts
        ansible.builtin.gather_facts:
  
      - name: Ensure required packages are installed (Apache, ModSecurity, Git)
        apt:
          name:
            - apache2
            - libapache2-mod-security2
            - git
          state: present
          update_cache: yes
  
      - name: Enable ModSecurity module
        apache2_module:
          name: security2
          state: present
  
      - name: Ensure the ModSecurity configuration file exists with correct content
        copy:
          dest: /etc/modsecurity/modsecurity.conf
          content: |
            # ModSecurity Configuration for Juice Shop
            SecRuleEngine On
            SecRequestBodyAccess On
            SecResponseBodyAccess Off
            SecRule REQUEST_HEADERS:User-Agent "libwww-perl" "id:1001,deny,status:403,msg:'Forbidden User-Agent'"
            SecRule ARGS|REQUEST_HEADERS|XML:/* "@rx some_pattern" "id:1002,phase:2,deny,status:403,msg:'Forbidden request pattern'"
          owner: root
          group: root
          mode: '0644'
          create: yes
  
      - name: Ensure modsecurity.conf file is present with action ID
        lineinfile:
          path: /etc/modsecurity/modsecurity.conf
          regexp: '^SecRule ARGS|REQUEST_HEADERS|XML:/*'
          line: "SecRule ARGS|REQUEST_HEADERS|XML:/* \"@rx some_pattern\" \"id:1002,phase:2,deny,status:403,msg:'Forbidden request pattern'\""
          create: yes
          backup: yes
  
      - name: Set paranoia level for ModSecurity in environment variable
        lineinfile:
          path: /etc/environment
          line: "PARANOIA=1"
          create: yes
  
      - name: Restart Apache to apply changes
        service:
          name: apache2
          state: restarted  