all:
  hosts:
    master:
      ansible_host: 192.168.1.12
    localhost:
      ansible_connection: local
  children:
    servers:
      hosts:
        server1:
          ansible_host: 192.168.1.11
...
